### ISSUE TITLE
Unable to detect Joplin port, caused by local proxy setting

### ISSUE THREAD

**Issue by hype1type** [jerrylususu/joplin-vacuum#1]
hi，man。I can't use your method, but I don't know what's wrong.
----------------------------------
D:\Downloads\Compressed\joplin-vacuum-main>python vacuum.py [D:\desk\27_04_2022.jex]
trying port 41184 not the port, skipping
trying port 41185 not the port, skipping
trying port 41186 not the port, skipping
trying port 41187 not the port, skipping
trying port 41188 not the port, skipping
trying port 41189 not the port, skipping
trying port 41190 not the port, skipping
trying port 41191 not the port, skipping
trying port 41192 not the port, skipping
trying port 41193 not the port, skipping
----------------------------------
port not found
Traceback (most recent call last):
  File "D:\Downloads\Compressed\joplin-vacuum-main\vacuum.py", line 207, in <module>
    main(args)
  File "D:\Downloads\Compressed\joplin-vacuum-main\vacuum.py", line 143, in main
    raise Exception("failed to connect to joplin port...")
Exception: failed to connect to joplin port...
----------------------------------

**Comment by jerrylususu** [comment]
Have you enabled the "web clipper" function? Joplin's Data API is only accessible with that function enabled. It can be enabled following these steps:
1. "Tools" Menu - Settings
2. On the left, choose "Web Clipper" (网页剪辑器)
3. On the right, find "Step 1" (步骤一), click "Enable Web Clipper" (启用网页剪辑器)

Please let me know if that works. I may have to update the README later to add this prerequisite.

**Comment by hype1type** [comment]
yes。
![1651065348(1)](https://user-images.githubusercontent.com/95662043/165526453-36e20139-f63d-47a6-b146-a9da7a8b2528.png)

**Comment by hype1type** [comment]
![image](https://user-images.githubusercontent.com/95662043/165526759-464c440d-6e04-42b4-906a-31c4cf01c180.png)

**Comment by jerrylususu** [comment]
Hi! Can you send a screenshot of your Joplin's version info? (Help - About Joplin)
Also, can you send a screenshot of using your browser to open `http://localhost:41184/ping`?

**Comment by hype1type** [comment]
![image](https://user-images.githubusercontent.com/95662043/165530263-2eec4ab2-bf07-4186-9704-edcc56db2590.png)

Joplin 2.7.15 (prod, win32)

客户端 ID: 78da96de37784085b80cd21b7fa0be6f
同步版本: 3
配置文件版本: 41
支持的密钥链: 是

修订: 8352e23

Thank you very much! I'm interrupting your time!
非常感谢您！打扰您的时间了！

**Comment by jerrylususu** [comment]
That's very strange. It seems that the port has been opened yet the script was unable to detect it. Can you save the following code into a Python file, run it and reply the result?

```python
import traceback
from urllib import request
import traceback
JOPLIN_PING_RESPONSE = "JoplinClipperServer"
port = 41184

req = request.Request(f"http://localhost:{port}/ping")
try:
    print("req begin")
    with request.urlopen(req) as f:
        print("rsp:", f.status, f.reason)
        rsp_text = f.read().decode("utf-8")
        print("text:", rsp_text)
        if f.status == 200 and rsp_text == JOPLIN_PING_RESPONSE:
            print("port find!")
    print("req done")
except Exception as e:
    print("not the port, skipping")
    traceback.print_exc()
```

**Comment by hype1type** [comment]
D:\pythonProject1\venv\Scripts\python.exe D:/pythonProject1/main.py
req begin
**Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 975, in send
    self.connect()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 941, in connect
    self.sock = self._create_connection(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\socket.py", line 845, in create_connection
    raise err
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pythonProject1\main.py", line 10, in <module>
    with request.urlopen(req) as f:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 1377, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。>**
not the port, skipping

进程已结束,退出代码0

**Comment by hype1type** [comment]
D:\pythonProject1\venv\Scripts\python.exe D:/pythonProject1/main.py
req begin
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 975, in send
    self.connect()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 941, in connect
    self.sock = self._create_connection(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\socket.py", line 845, in create_connection
    raise err
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pythonProject1\main.py", line 10, in <module>
    with request.urlopen(req) as f:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 1377, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。>
not the port, skipping

进程已结束,退出代码0

**Comment by jerrylususu** [comment]
This is even stranger. I have no idea on why Chrome can access this port but not the script. Can you disable your antivirus software (if any) and Windows Firewall, then try again?

**Comment by jerrylususu** [comment]
Also, can you run the following command in a command prompt and paste the result?

`curl http://localhost:41184/ping -v`

**Comment by hype1type** [comment]
According to your method, turn off the anti-virus software and it still can't be solved. The following is the information provided by CMD.
----------------------------
C:\Users\HP>curl http://localhost:41184/ping -v
*   Trying 127.0.0.1:41184...
*   Trying ::1:41184...
* connect to 127.0.0.1 port 41184 failed: Connection refused
* connect to ::1 port 41184 failed: Connection refused
* Failed to connect to localhost port 41184 after 2232 ms: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 41184 after 2232 ms: Connection refused

**Comment by jerrylususu** [comment]
Sadly at this step I can not give any further advice. From my understanding, it seems that Chrome is able to access Joplin's API port, but not the command line tools. I would suspect there might be some issues in your network / firewall / loopback setting.  Perhaps you can try to update your Joplin version to the newest, but I am not sure whether this will work. Or you can try restart Joplin / Windows.

**Comment by hype1type** [comment]
Thank you very much for your help and time. I will continue to try according to your method.

**Comment by jerrylususu** [comment]
Do you have any proxy service running locally? Have you tried to disable that?

**Comment by hype1type** [comment]
wow！！！
something change！

D:\Downloads\Compressed\joplin-vacuum-main>python vacuum.py [D:\desk\27_04_2022.jex]
trying port 41183 not the port, skipping
trying port 41184 200 OK port find!
no existing token found, requesting
200 OK
Token requested. Please check the joplin app to grant access.
Press enter after granting access.
----------------------------------------------------------
【Do you have any proxy service running locally? Have you tried to disable that?】

**Comment by jerrylususu** [comment]
Great. On this step, you need to open Joplin, click "Grant Access" (授权), return to the script and press enter.

**Comment by hype1type** [comment]
thank!!! I'll try and tell you the news! Thank you very much     
![image](https://user-images.githubusercontent.com/95662043/165541756-4947dc93-c2d1-4e96-9ba1-1887327af799.png)

**Comment by hype1type** [comment]
![image](https://user-images.githubusercontent.com/95662043/165545568-5cfe1038-a78e-4335-9084-bb86a8781eb4.png)
❤🌹🌹🌹🌹🌹🌹🌹🌹🌹🌹🌹
